openapi: 3.0.3
info:
  title: Магазин автозапчастей
  description: Развалов Никита 23-ИСбо-1
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1/
    description: dev server
paths:
  /sparts:
    get:
      summary: Метод получения запчастей
      tags:
        - SpareParts
      operationId: getAllParts
      parameters:
        - name: page
          in: query
          description: Номер страницы
          schema:
            type: integer
            example: 1
        - name: page_size
          in: query
          description: Количество элементов на странице
          schema:
            type: integer
            example: 5
      responses:
        "200":
          description: "Условный ответ со списком запчастей"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SparePagination"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания запчасти
      tags:
        - SpareParts
      operationId: createSPart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SparePart"
      responses:
        "200":
          description: "Условный ответ с созданной запчастью"
          content:
            application/json:
              schema:
                properties:
                  pagination:
                    $ref: "#/components/schemas/SparePagination"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sparts/{spare_id}:
    get:
      summary: Метод получения запчасти по идентификатору
      tags:
        - SpareParts
      operationId: getAllPartsById
      parameters: 
        - name: spare_id
          in: path
          required: true
          description: Идентификатор запчасти
          schema:
            type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
      responses:
        "200":
          description: "Условный ответ с запчастью"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SparePart"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления
      tags:
        - SpareParts
      operationId: deleteSparePartById
      parameters: 
        - name: spare_id
          in: path
          required: true
          description: Идентификатор запчасти
          schema:
            type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
      responses:
        "200":
          description: "Успешное удаление"
          content:
            application/json: {} #ничё не возвращаем
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /orders:
    get:
      summary: Получение списка заказов
      tags:
        - Orders
      operationId: getAllOrders
      parameters:
        - name: page
          in: query
          description: Номер страницы
          schema:
            type: integer
            example: 1
        - name: page_size
          in: query
          description: Количество элементов на странице
          schema:
            type: integer
            example: 5
      responses:
        "200":
          description: "Список заказов"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderPagination"
        "default":
          description: всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания заказа
      tags:
        - Orders
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: "Заказ создан"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "default":
          description: всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /orders/{order_id}:
    get:
      summary: Получение заказа по идентификатору
      tags:
        - Orders
      operationId: getOrderById
      parameters:
        - name: order_id
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: string
          example: "42abcd2b-8b9c-4af9-88f7-0bc100fc74b"
      responses:
        "200":
          description: "Информация о заказе"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "default":
          description: всё что не 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления заказа
      tags:
        - Orders
      operationId: deleteOrderById
      parameters: 
        - name: order_id
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
      responses:
        "200":
          description: "Успешное удаление"
          content:
            application/json: {} #ничё не возвращаем
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cart:
    get:
      summary: Метод получения содержимого корзины
      tags: 
        - Cart
      operationId: getCart
      responses:
          "200":
            description: "Информация о заказе"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Cart"
          "default":
            description: всё что не 200
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/Error"
    post:
      summary: Метод добавления запчасти в корзину
      tags:
        - Cart
      operationId: addToCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartItem"
      responses:
        "200":
          description: "Запчасть добавлена в корзину"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "default":
          description: всё что не 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cart/{spare_id}:
    delete:
      summary: Удаление запчасти из корзины
      tags:
        - Cart
      operationId: removeFromCart
      responses:
        "200":
          description: "Запчасть удалена из корзины"
          content:
            application/json: {}
        "default":
          description: всё что не 200
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    SparePart:
      type: object
      required:
        - articul
        - spare_id
        - name
        - price
        - status 
      properties:
        articul:
          type: string
          example: MR497143
        spare_id:
          type: string
          example: "42abcd2b-8b9c-4af9-88f7-0bc100fc74b"
        name:
          type: string
          example: Дверь
        price:
          type: integer
          format: float
          example: 5000.59
        status:
          type: string
          enum:
           - new
           - old
          description: Состояние запчасти
    SpareParts:
        type: array
        items:
          $ref: "#/components/schemas/SparePart" #ссылаемся на запчасть
    Order:
      type: object
      required:
        - spareparts
        - amount
      properties:
        spareparts:
          type: array
          items: 
            $ref: "#/components/schemas/SparePart"
        amount:
            type: number
            format: float
            example: 5000.59
        status:
            enum:
            - processing
            - completed
            description: Статус заказа
        created_at:
            type: string
            format: date-time
            example: "2025-03-27T12:00:00Z"
    Orders:
        type: array
        items:
          $ref: "#/components/schemas/Order" #ссылаемся на запчасть
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    CartItem:
      type: object
      required:
        - articul
        - name
        - spare_id
        - quantity
      properties:
        articul:
          type: string
          example: "MR497345"
        name:
          type: string
          example: "Дверь"
        spare_id:
          type: string
          example: "42abcd2b-8b9c-4af9-88f7-0bc100fc74b"
        quantity:
          type: integer
          example: 2
    Cart:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
    SparePagination:
      type: object
      properties:
        count:
          type: integer
          description: Общее количество запчастей
          example: 1
        results:
          type: array
          items:
            $ref: "#/components/schemas/SparePart"
    OrderPagination:
      type: object
      properties:
        count:
          type: integer
          description: Общее количество заказов
          example: 1
        results:
          type: array
          items:
            $ref: "#/components/schemas/Order"