openapi: 3.0.3
info:
  title: Магазин запчастей
  description: Развалов Никита 23-ИСбо-1
  version: 0.0.1
servers:
  - url: http://localhost:8000/api/v1/
    description: dev server
paths:
  /sparts:
    get:
      summary: Метод получения запчастей
      tags:
        - SpareParts
      operationId: getAllParts
      responses:
        "200":
          description: "Условный ответ со списком запчастей"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SpareParts"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания запчасти
      tags:
        - SpareParts
      operationId: createSPart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SparePart"
      responses:
        "200":
          description: "Условный ответ с созданной запчастью"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SparePart"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sparts/{spare_id}:
    get:
      summary: Метод получения запчасти по идентификатору
      tags:
        - SpareParts
      operationId: getAllPartsById
      parameters: 
        - name: spare_id
          in: path
          required: true
          description: Идентификатор запчасти
          schema:
            type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
      responses:
        "200":
          description: "Условный ответ с запчастью"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SparePart"
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Метод удаления
      tags:
        - SpareParts
      operationId: deleteSparePartById
      parameters: 
        - name: spare_id
          in: path
          required: true
          description: Идентификатор запчасти
          schema:
            type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
      responses:
        "200":
          description: "Успешное удаление"
          content:
            application/json: {} #ничё не возвращаем
        "default": #всё что не 200
          description: Всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /orders:
    get:
      summary: Получение списка заказов
      tags:
        - Orders
      operationId: getAllOrders
      responses:
        "200":
          description: "Список заказов"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
        "default":
          description: всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод создания заказа
      tags:
        - Orders
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: "Заказ создан"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "default":
          description: всё нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /orders/{order_id}:
    get:
      summary: Получение заказа по идентификатору
      tags:
        - Orders
      operationId: getOrderById
      parameters:
        - name: order_id
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: string
          example: "42abcd2b-8b9c-4af9-88f7-0bc100fc74b"
      responses:
        "200":
          description: "Информация о заказе"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "default":
          description: Ошибка
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  

components:
  schemas:
    SparePart:
      type: object
      required:
        - name
        - status 
      properties:
        spare_id:
          type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
        name:
          type: string
          example: Дверь
        status:
          type: string
          enum:
           - new
           - old
           - broken
          description: Состояние запчасти
        created_at:
           type: string
           format: 2025-03-01T15:00:00:01
    SpareParts:
        type: array
        items:
          $ref: "#/components/schemas/SparePart" #ссылаемся на запчасть
    Order:
      type: object
      required:
        - order_id
        - spareparts
        - price
      properties:
        order_id:
          type: string
          example: 42abcd2b-8b9c-4af9-88f7-0bc100fc74b
        spareparts:
          type: array
          items: 
            $ref: "#/components/schemas/SparePart"
        price:
            type: number
            format: float
            example: 5500.59
        status:
            enum:
            - pending
            - processing
            - shipped
            - delivered
            description: Статус заказа
        created_at:
            type: string
            format: date-time
            example: "2025-03-27T12:00:00Z"
    Orders:
        type: array
        items:
          $ref: "#/components/schemas/Order" #ссылаемся на запчасть
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string